// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000/api' | (string & {});
};

export type RegisterInput = {
    email: string;
    name: string;
    nim: string;
    password: string;
    passwordConfirmation: string;
};

export type LoginInput = {
    email: string;
    password: string;
};

export type ChangePasswordInput = {
    oldPassword: string;
    newPassword: string;
    passwordConfirmation: string;
};

export type UserInput = {
    name: string;
    email: string;
    password: string;
};

export type UserUpdateInput = {
    name?: string;
    email?: string;
};

export type UserListItem = {
    id: string;
    name: string;
    email: string;
    isActive: boolean;
    role: {
        name: string;
    };
};

export type UserById = {
    id: string;
    name: string;
    email: string;
    isActive: boolean;
    role: {
        name: string;
    };
};

export type CreateBuildingInput = {
    name: string;
};

export type UpdateBuildingInput = {
    name?: string;
};

export type Building = {
    id: string;
    name: string;
    createdAt: string | null;
};

export type CreateRoomInput = {
    name: string;
    buildingId: string;
    floor: number;
};

export type UpdateRoomInput = {
    name?: string;
    buildingId?: string;
    floor?: number;
};

export type Room = {
    id: string;
    name: string;
    buildingId: string;
    createdAt: string | null;
    floor: number;
};

export type CreateReportInput = {
    roomId: string;
    description: string;
    image?: Blob | File;
    status?: 'REPORTED' | 'IN_PROGRESS' | 'RESOLVED';
    isUrgent?: boolean;
    categoryId: string;
};

export type UpdateReportInput = {
    roomId?: string;
    description?: string;
    image?: Blob | File;
    status?: 'REPORTED' | 'IN_PROGRESS' | 'RESOLVED';
    isUrgent?: boolean;
    categoryId?: string;
};

export type Report = {
    id: string;
    reporterId: string;
    roomId: string;
    description: string | null;
    imageUrl: string | null;
    status: string | null;
    isUrgent: boolean;
    categoryId: string;
    createdAt: string | null;
};

export type CreateCategoryInput = {
    name: string;
};

export type UpdateCategoryInput = {
    name?: string;
};

export type Category = {
    id: string;
    name: string;
    createdAt: string | null;
};

export type ErrorResponse = {
    success: false;
    message: string;
};

export type ValidationErrorResponse = {
    success: false;
    message: string;
    errors: Array<{
        field: string;
        message: string;
    }>;
};

export type DashboardResponse = {
    summary: {
        totalReports: number;
        pendingReports: number;
        resolvedReports: number;
    };
    categoryTrend: Array<{
        categoryName: string;
        count: number;
    }>;
    topRooms: Array<{
        roomName: string;
        floor: number;
        buildingName: string;
        count: number;
    }>;
};

export type PostAuthRegisterData = {
    body?: {
        email: string;
        name: string;
        nim: string;
        password: string;
        passwordConfirmation: string;
    };
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Conflict — user or NIM already exists
     */
    409: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * User registered successfully
     */
    201: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        };
    };
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
    body?: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Invalid credentials
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success: boolean;
        message: string;
        data: {
            token: string;
            user: {
                id: string;
                name: string;
                email: string;
                isActive: boolean;
                role: {
                    name: string;
                };
            };
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PutAuthChangePasswordData = {
    body?: {
        oldPassword: string;
        newPassword: string;
        passwordConfirmation: string;
    };
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type PutAuthChangePasswordErrors = {
    /**
     * Bad request — passwords do not match
     */
    400: {
        success: false;
        message: string;
    };
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PutAuthChangePasswordError = PutAuthChangePasswordErrors[keyof PutAuthChangePasswordErrors];

export type PutAuthChangePasswordResponses = {
    /**
     * Password changed successfully
     */
    200: {
        success: boolean;
        message: string;
    };
};

export type PutAuthChangePasswordResponse = PutAuthChangePasswordResponses[keyof PutAuthChangePasswordResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * Users fetched successfully
     */
    200: {
        success: boolean;
        message: string;
        data: Array<{
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        }>;
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersObData = {
    body?: {
        name: string;
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/users/OB';
};

export type PostUsersObErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Role OB not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Conflict — user already exists
     */
    409: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PostUsersObError = PostUsersObErrors[keyof PostUsersObErrors];

export type PostUsersObResponses = {
    /**
     * OB user created successfully
     */
    201: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        };
    };
};

export type PostUsersObResponse = PostUsersObResponses[keyof PostUsersObResponses];

export type PostUsersAdminData = {
    body?: {
        name: string;
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/users/admin';
};

export type PostUsersAdminErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Role Admin not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Conflict — user already exists
     */
    409: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PostUsersAdminError = PostUsersAdminErrors[keyof PostUsersAdminErrors];

export type PostUsersAdminResponses = {
    /**
     * Admin user created successfully
     */
    201: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        };
    };
};

export type PostUsersAdminResponse = PostUsersAdminResponses[keyof PostUsersAdminResponses];

export type GetUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * User not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type GetUsersByIdError = GetUsersByIdErrors[keyof GetUsersByIdErrors];

export type GetUsersByIdResponses = {
    /**
     * User fetched successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        };
    };
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type PutUsersByIdData = {
    body?: {
        name?: string;
        email?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type PutUsersByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * User not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PutUsersByIdError = PutUsersByIdErrors[keyof PutUsersByIdErrors];

export type PutUsersByIdResponses = {
    /**
     * User updated successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        };
    };
};

export type PutUsersByIdResponse = PutUsersByIdResponses[keyof PutUsersByIdResponses];

export type PatchUsersByIdStatusData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}/status';
};

export type PatchUsersByIdStatusErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * User not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PatchUsersByIdStatusError = PatchUsersByIdStatusErrors[keyof PatchUsersByIdStatusErrors];

export type PatchUsersByIdStatusResponses = {
    /**
     * User status updated successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        };
    };
};

export type PatchUsersByIdStatusResponse = PatchUsersByIdStatusResponses[keyof PatchUsersByIdStatusResponses];

export type GetBuildingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buildings';
};

export type GetBuildingsErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type GetBuildingsError = GetBuildingsErrors[keyof GetBuildingsErrors];

export type GetBuildingsResponses = {
    /**
     * Buildings fetched successfully
     */
    200: {
        success: boolean;
        message: string;
        data: Array<{
            id: string;
            name: string;
            createdAt: string | null;
        }>;
    };
};

export type GetBuildingsResponse = GetBuildingsResponses[keyof GetBuildingsResponses];

export type PostBuildingsData = {
    body?: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/buildings';
};

export type PostBuildingsErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PostBuildingsError = PostBuildingsErrors[keyof PostBuildingsErrors];

export type PostBuildingsResponses = {
    /**
     * Building created successfully
     */
    201: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            createdAt: string | null;
        };
    };
};

export type PostBuildingsResponse = PostBuildingsResponses[keyof PostBuildingsResponses];

export type DeleteBuildingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/buildings/{id}';
};

export type DeleteBuildingsByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Building not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type DeleteBuildingsByIdError = DeleteBuildingsByIdErrors[keyof DeleteBuildingsByIdErrors];

export type DeleteBuildingsByIdResponses = {
    /**
     * Building deleted successfully
     */
    200: {
        success: boolean;
        message: string;
    };
};

export type DeleteBuildingsByIdResponse = DeleteBuildingsByIdResponses[keyof DeleteBuildingsByIdResponses];

export type GetBuildingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/buildings/{id}';
};

export type GetBuildingsByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Building not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type GetBuildingsByIdError = GetBuildingsByIdErrors[keyof GetBuildingsByIdErrors];

export type GetBuildingsByIdResponses = {
    /**
     * Building fetched successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            createdAt: string | null;
        };
    };
};

export type GetBuildingsByIdResponse = GetBuildingsByIdResponses[keyof GetBuildingsByIdResponses];

export type PutBuildingsByIdData = {
    body?: {
        name?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/buildings/{id}';
};

export type PutBuildingsByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Building not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PutBuildingsByIdError = PutBuildingsByIdErrors[keyof PutBuildingsByIdErrors];

export type PutBuildingsByIdResponses = {
    /**
     * Building updated successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            createdAt: string | null;
        };
    };
};

export type PutBuildingsByIdResponse = PutBuildingsByIdResponses[keyof PutBuildingsByIdResponses];

export type GetRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type GetRoomsErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type GetRoomsError = GetRoomsErrors[keyof GetRoomsErrors];

export type GetRoomsResponses = {
    /**
     * Rooms fetched successfully
     */
    200: {
        success: boolean;
        message: string;
        data: Array<{
            id: string;
            name: string;
            buildingId: string;
            createdAt: string | null;
            floor: number;
        }>;
    };
};

export type GetRoomsResponse = GetRoomsResponses[keyof GetRoomsResponses];

export type PostRoomsData = {
    body?: {
        name: string;
        buildingId: string;
        floor: number;
    };
    path?: never;
    query?: never;
    url: '/rooms';
};

export type PostRoomsErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PostRoomsError = PostRoomsErrors[keyof PostRoomsErrors];

export type PostRoomsResponses = {
    /**
     * Room created successfully
     */
    201: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            buildingId: string;
            createdAt: string | null;
            floor: number;
        };
    };
};

export type PostRoomsResponse = PostRoomsResponses[keyof PostRoomsResponses];

export type DeleteRoomsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type DeleteRoomsByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Room not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type DeleteRoomsByIdError = DeleteRoomsByIdErrors[keyof DeleteRoomsByIdErrors];

export type DeleteRoomsByIdResponses = {
    /**
     * Room deleted successfully
     */
    200: {
        success: boolean;
        message: string;
    };
};

export type DeleteRoomsByIdResponse = DeleteRoomsByIdResponses[keyof DeleteRoomsByIdResponses];

export type GetRoomsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type GetRoomsByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Room not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type GetRoomsByIdError = GetRoomsByIdErrors[keyof GetRoomsByIdErrors];

export type GetRoomsByIdResponses = {
    /**
     * Room fetched successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            buildingId: string;
            createdAt: string | null;
            floor: number;
        };
    };
};

export type GetRoomsByIdResponse = GetRoomsByIdResponses[keyof GetRoomsByIdResponses];

export type PutRoomsByIdData = {
    body?: {
        name?: string;
        buildingId?: string;
        floor?: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type PutRoomsByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Room not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PutRoomsByIdError = PutRoomsByIdErrors[keyof PutRoomsByIdErrors];

export type PutRoomsByIdResponses = {
    /**
     * Room updated successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            buildingId: string;
            createdAt: string | null;
            floor: number;
        };
    };
};

export type PutRoomsByIdResponse = PutRoomsByIdResponses[keyof PutRoomsByIdResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type GetCategoriesErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type GetCategoriesError = GetCategoriesErrors[keyof GetCategoriesErrors];

export type GetCategoriesResponses = {
    /**
     * Categories fetched successfully
     */
    200: {
        success: boolean;
        message: string;
        data: Array<{
            id: string;
            name: string;
            createdAt: string | null;
        }>;
    };
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type PostCategoriesData = {
    body?: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/categories';
};

export type PostCategoriesErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PostCategoriesError = PostCategoriesErrors[keyof PostCategoriesErrors];

export type PostCategoriesResponses = {
    /**
     * Category created successfully
     */
    201: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            createdAt: string | null;
        };
    };
};

export type PostCategoriesResponse = PostCategoriesResponses[keyof PostCategoriesResponses];

export type DeleteCategoriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/categories/{id}';
};

export type DeleteCategoriesByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Category not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type DeleteCategoriesByIdError = DeleteCategoriesByIdErrors[keyof DeleteCategoriesByIdErrors];

export type DeleteCategoriesByIdResponses = {
    /**
     * Category deleted successfully
     */
    200: {
        success: boolean;
        message: string;
    };
};

export type DeleteCategoriesByIdResponse = DeleteCategoriesByIdResponses[keyof DeleteCategoriesByIdResponses];

export type GetCategoriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/categories/{id}';
};

export type GetCategoriesByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Category not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type GetCategoriesByIdError = GetCategoriesByIdErrors[keyof GetCategoriesByIdErrors];

export type GetCategoriesByIdResponses = {
    /**
     * Category fetched successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            createdAt: string | null;
        };
    };
};

export type GetCategoriesByIdResponse = GetCategoriesByIdResponses[keyof GetCategoriesByIdResponses];

export type PutCategoriesByIdData = {
    body?: {
        name?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/categories/{id}';
};

export type PutCategoriesByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Category not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PutCategoriesByIdError = PutCategoriesByIdErrors[keyof PutCategoriesByIdErrors];

export type PutCategoriesByIdResponses = {
    /**
     * Category updated successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            id: string;
            name: string;
            createdAt: string | null;
        };
    };
};

export type PutCategoriesByIdResponse = PutCategoriesByIdResponses[keyof PutCategoriesByIdResponses];

export type GetReportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reports';
};

export type GetReportsErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type GetReportsError = GetReportsErrors[keyof GetReportsErrors];

export type GetReportsResponses = {
    /**
     * Reports fetched successfully
     */
    200: {
        success: boolean;
        message: string;
        data: Array<{
            id: string;
            reporterId: string;
            roomId: string;
            description: string | null;
            imageUrl: string | null;
            status: string | null;
            isUrgent: boolean;
            categoryId: string;
            createdAt: string | null;
        }>;
    };
};

export type GetReportsResponse = GetReportsResponses[keyof GetReportsResponses];

export type PostReportsData = {
    body?: {
        roomId: string;
        description: string;
        image?: Blob | File;
        status?: 'REPORTED' | 'IN_PROGRESS' | 'RESOLVED';
        isUrgent?: boolean;
        categoryId: string;
    };
    path?: never;
    query?: never;
    url: '/reports';
};

export type PostReportsErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PostReportsError = PostReportsErrors[keyof PostReportsErrors];

export type PostReportsResponses = {
    /**
     * Report created successfully
     */
    201: {
        success: boolean;
        message: string;
        data: {
            id: string;
            reporterId: string;
            roomId: string;
            description: string | null;
            imageUrl: string | null;
            status: string | null;
            isUrgent: boolean;
            categoryId: string;
            createdAt: string | null;
        };
    };
};

export type PostReportsResponse = PostReportsResponses[keyof PostReportsResponses];

export type DeleteReportsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/reports/{id}';
};

export type DeleteReportsByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Report not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type DeleteReportsByIdError = DeleteReportsByIdErrors[keyof DeleteReportsByIdErrors];

export type DeleteReportsByIdResponses = {
    /**
     * Report deleted successfully
     */
    200: {
        success: boolean;
        message: string;
    };
};

export type DeleteReportsByIdResponse = DeleteReportsByIdResponses[keyof DeleteReportsByIdResponses];

export type GetReportsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/reports/{id}';
};

export type GetReportsByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Report not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type GetReportsByIdError = GetReportsByIdErrors[keyof GetReportsByIdErrors];

export type GetReportsByIdResponses = {
    /**
     * Report fetched successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            id: string;
            reporterId: string;
            roomId: string;
            description: string | null;
            imageUrl: string | null;
            status: string | null;
            isUrgent: boolean;
            categoryId: string;
            createdAt: string | null;
        };
    };
};

export type GetReportsByIdResponse = GetReportsByIdResponses[keyof GetReportsByIdResponses];

export type PatchReportsByIdData = {
    body?: {
        roomId?: string;
        description?: string;
        image?: Blob | File;
        status?: 'REPORTED' | 'IN_PROGRESS' | 'RESOLVED';
        isUrgent?: boolean;
        categoryId?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/reports/{id}';
};

export type PatchReportsByIdErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Report not found
     */
    404: {
        success: false;
        message: string;
    };
    /**
     * Validation failed
     */
    422: {
        success: false;
        message: string;
        errors: Array<{
            field: string;
            message: string;
        }>;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type PatchReportsByIdError = PatchReportsByIdErrors[keyof PatchReportsByIdErrors];

export type PatchReportsByIdResponses = {
    /**
     * Report updated successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            id: string;
            reporterId: string;
            roomId: string;
            description: string | null;
            imageUrl: string | null;
            status: string | null;
            isUrgent: boolean;
            categoryId: string;
            createdAt: string | null;
        };
    };
};

export type PatchReportsByIdResponse = PatchReportsByIdResponses[keyof PatchReportsByIdResponses];

export type GetReportsDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reports/dashboard';
};

export type GetReportsDashboardErrors = {
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type GetReportsDashboardError = GetReportsDashboardErrors[keyof GetReportsDashboardErrors];

export type GetReportsDashboardResponses = {
    /**
     * Dashboard stats fetched successfully
     */
    200: {
        success: boolean;
        message: string;
        data: {
            summary: {
                totalReports: number;
                pendingReports: number;
                resolvedReports: number;
            };
            categoryTrend: Array<{
                categoryName: string;
                count: number;
            }>;
            topRooms: Array<{
                roomName: string;
                floor: number;
                buildingName: string;
                count: number;
            }>;
        };
    };
};

export type GetReportsDashboardResponse = GetReportsDashboardResponses[keyof GetReportsDashboardResponses];

export type GetReportsExportCsvData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by month (1-12)
         */
        month?: number;
        /**
         * Filter by year (e.g. 2026)
         */
        year?: number;
    };
    url: '/reports/export/csv';
};

export type GetReportsExportCsvErrors = {
    /**
     * Invalid query parameters
     */
    400: {
        success: false;
        message: string;
    };
    /**
     * Unauthenticated — token missing or invalid
     */
    401: {
        success: false;
        message: string;
    };
    /**
     * Forbidden — insufficient permissions
     */
    403: {
        success: false;
        message: string;
    };
    /**
     * Internal server error
     */
    500: {
        success: false;
        message: string;
    };
};

export type GetReportsExportCsvError = GetReportsExportCsvErrors[keyof GetReportsExportCsvErrors];

export type GetReportsExportCsvResponses = {
    /**
     * CSV file content
     */
    200: string;
};

export type GetReportsExportCsvResponse = GetReportsExportCsvResponses[keyof GetReportsExportCsvResponses];
