// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000/api' | (string & {});
};

export type RegisterInput = {
    email: string;
    name: string;
    nim: string;
    password: string;
    passwordConfirmation: string;
};

export type LoginInput = {
    email: string;
    password: string;
};

export type ChangePasswordInput = {
    oldPassword: string;
    newPassword: string;
    passwordConfirmation: string;
};

export type UserInput = {
    name: string;
    email: string;
    password: string;
};

export type PostAuthRegisterData = {
    body?: {
        email: string;
        name: string;
        nim: string;
        password: string;
        passwordConfirmation: string;
    };
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterResponses = {
    /**
     * Success Response
     */
    201: {
        status: string;
        message: string;
        data?: unknown;
    };
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
    body?: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: {
            token: string;
            user?: unknown;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PutAuthChangePasswordData = {
    body?: {
        oldPassword: string;
        newPassword: string;
        passwordConfirmation: string;
    };
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type PutAuthChangePasswordResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
    };
};

export type PutAuthChangePasswordResponse = PutAuthChangePasswordResponses[keyof PutAuthChangePasswordResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: Array<unknown>;
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data?: unknown;
    };
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];
