// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000/api' | (string & {});
};

export type RegisterInput = {
    email: string;
    name: string;
    nim: string;
    password: string;
    passwordConfirmation: string;
};

export type LoginInput = {
    email: string;
    password: string;
};

export type ChangePasswordInput = {
    oldPassword: string;
    newPassword: string;
    passwordConfirmation: string;
};

export type UserInput = {
    name: string;
    email: string;
    password: string;
};

export type UserUpdateInput = {
    name?: string;
    email?: string;
};

export type UserListItem = {
    id: string;
    name: string;
    email: string;
    isActive: boolean;
    role: {
        name: string;
    };
};

export type UserById = {
    id: string;
    name: string;
    email: string;
    isActive: boolean;
    role: {
        name: string;
    };
};

export type CreateBuildingInput = {
    name: string;
};

export type UpdateBuildingInput = {
    name?: string;
};

export type Building = {
    id: string;
    name: string;
    createdAt: string | null;
};

export type CreateRoomInput = {
    name: string;
    buildingId: string;
    floor: number;
};

export type UpdateRoomInput = {
    name?: string;
    buildingId?: string;
    floor?: number;
};

export type Room = {
    id: string;
    name: string;
    buildingId: string;
    createdAt: string | null;
    floor: number;
};

export type PostAuthRegisterData = {
    body?: {
        email: string;
        name: string;
        nim: string;
        password: string;
        passwordConfirmation: string;
    };
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterResponses = {
    /**
     * Success Response
     */
    201: {
        status: string;
        message: string;
        data: {
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        };
    };
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
    body?: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: {
            token: string;
            user: {
                id: string;
                name: string;
                email: string;
                isActive: boolean;
                role: {
                    name: string;
                };
            };
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PutAuthChangePasswordData = {
    body?: {
        oldPassword: string;
        newPassword: string;
        passwordConfirmation: string;
    };
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type PutAuthChangePasswordResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
    };
};

export type PutAuthChangePasswordResponse = PutAuthChangePasswordResponses[keyof PutAuthChangePasswordResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: Array<{
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        }>;
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersObData = {
    body?: {
        name: string;
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/users/OB';
};

export type PostUsersObResponses = {
    /**
     * Success Response
     */
    201: {
        status: string;
        message: string;
        data: {
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        };
    };
};

export type PostUsersObResponse = PostUsersObResponses[keyof PostUsersObResponses];

export type GetUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: {
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        };
    };
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type PutUsersByIdData = {
    body?: {
        name?: string;
        email?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type PutUsersByIdResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: {
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        };
    };
};

export type PutUsersByIdResponse = PutUsersByIdResponses[keyof PutUsersByIdResponses];

export type PatchUsersByIdStatusData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}/status';
};

export type PatchUsersByIdStatusResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: {
            id: string;
            name: string;
            email: string;
            isActive: boolean;
            role: {
                name: string;
            };
        };
    };
};

export type PatchUsersByIdStatusResponse = PatchUsersByIdStatusResponses[keyof PatchUsersByIdStatusResponses];

export type GetBuildingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buildings';
};

export type GetBuildingsResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: Array<{
            id: string;
            name: string;
            createdAt: string | null;
        }>;
    };
};

export type GetBuildingsResponse = GetBuildingsResponses[keyof GetBuildingsResponses];

export type PostBuildingsData = {
    body?: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/buildings';
};

export type PostBuildingsResponses = {
    /**
     * Success Response
     */
    201: {
        status: string;
        message: string;
        data: {
            id: string;
            name: string;
            createdAt: string | null;
        };
    };
};

export type PostBuildingsResponse = PostBuildingsResponses[keyof PostBuildingsResponses];

export type DeleteBuildingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/buildings/{id}';
};

export type DeleteBuildingsByIdResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
    };
};

export type DeleteBuildingsByIdResponse = DeleteBuildingsByIdResponses[keyof DeleteBuildingsByIdResponses];

export type GetBuildingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/buildings/{id}';
};

export type GetBuildingsByIdResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: {
            id: string;
            name: string;
            createdAt: string | null;
        };
    };
};

export type GetBuildingsByIdResponse = GetBuildingsByIdResponses[keyof GetBuildingsByIdResponses];

export type PutBuildingsByIdData = {
    body?: {
        name?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/buildings/{id}';
};

export type PutBuildingsByIdResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: {
            id: string;
            name: string;
            createdAt: string | null;
        };
    };
};

export type PutBuildingsByIdResponse = PutBuildingsByIdResponses[keyof PutBuildingsByIdResponses];

export type GetRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type GetRoomsResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: Array<{
            id: string;
            name: string;
            buildingId: string;
            createdAt: string | null;
            floor: number;
        }>;
    };
};

export type GetRoomsResponse = GetRoomsResponses[keyof GetRoomsResponses];

export type PostRoomsData = {
    body?: {
        name: string;
        buildingId: string;
        floor: number;
    };
    path?: never;
    query?: never;
    url: '/rooms';
};

export type PostRoomsResponses = {
    /**
     * Success Response
     */
    201: {
        status: string;
        message: string;
        data: {
            id: string;
            name: string;
            buildingId: string;
            createdAt: string | null;
            floor: number;
        };
    };
};

export type PostRoomsResponse = PostRoomsResponses[keyof PostRoomsResponses];

export type DeleteRoomsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type DeleteRoomsByIdResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
    };
};

export type DeleteRoomsByIdResponse = DeleteRoomsByIdResponses[keyof DeleteRoomsByIdResponses];

export type GetRoomsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type GetRoomsByIdResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: {
            id: string;
            name: string;
            buildingId: string;
            createdAt: string | null;
            floor: number;
        };
    };
};

export type GetRoomsByIdResponse = GetRoomsByIdResponses[keyof GetRoomsByIdResponses];

export type PutRoomsByIdData = {
    body?: {
        name?: string;
        buildingId?: string;
        floor?: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type PutRoomsByIdResponses = {
    /**
     * Success Response
     */
    200: {
        status: string;
        message: string;
        data: {
            id: string;
            name: string;
            buildingId: string;
            createdAt: string | null;
            floor: number;
        };
    };
};

export type PutRoomsByIdResponse = PutRoomsByIdResponses[keyof PutRoomsByIdResponses];
